### ISSUE TITLE
Doesn`t work for spark 2.4.0-scala 2.11 and python 3.6.9

### ISSUE THREAD

**Issue by Jewen94** [arangodb/arangodb-spark-datasource#43]
Hi!

My installation is
```
spark: 2.4.0
scala: 2.11
python: 3.6.9
arangodb-spark-datasource:  2.4_2.11:1.4.3
arangodb: 3.10 (cluster)
```

When I try to use driver com.arangodb:arangodb-spark-datasource-2.4_2.11:1.4.3, I get this error ->

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/spark/python/pyspark/sql/dataframe.py", line 378, in show
    print(self._jdf.showString(n, 20, vertical))
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/local/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o46.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.util.CaseInsensitiveMap.$plus(Lscala/Tuple2;)Lorg/apache/spark/sql/catalyst/util/CaseInsensitiveMap;
	at org.apache.spark.sql.arangodb.commons.ArangoDBConf.updated(ArangoDBConf.scala:357)
	at org.apache.spark.sql.arangodb.datasource.reader.ArangoCollectionPartitionReader.<init>(ArangoCollectionPartitionReader.scala:25)
	at org.apache.spark.sql.arangodb.datasource.reader.ArangoCollectionPartition.createPartitionReader(ArangoCollectionPartition.scala:23)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD.compute(DataSourceRDD.scala:42)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Here is my code in pypspark (this data from demo):

```
pyspark --packages com.arangodb:arangodb-spark-datasource-2.4_2.11:1.4.3

ar_options = {
  "database": "test",
  "user": "root",
  "password": "test",
  "endpoints": "localhost:8529",
  "table": "persons",
}

from pyspark.sql.types import StructType, StructField, StringType, TimestampType, DateType, IntegerType
person_schema: StructType = StructType([
    StructField("_id", StringType(), nullable=False),
    StructField("_key", StringType(), nullable=False),
    StructField("biography", StringType()),
    StructField("birthday", DateType()),
    StructField("birthplace", StringType()),
    StructField("lastModified", TimestampType()),
    StructField("name", StringType()),
    StructField("profileImageUrl", StringType())
])
df_test2 = spark.read.format("com.arangodb.spark").options(**ar_options).schema(person_schema).load()
df_test2.show(5, False)
```

On spark 3.2 and python 3.10 it is working without any problems

Could you help?

**Comment by rashtao** [comment]
Spark `2.4.0` is quite old, can you try with Spark `2.4.8`?

**Comment by Jewen94** [comment]
I tried it.
It is working.
Thanks for quick response
